package com.simplehttp

/**
 * Created by basca on 04/06/14.
 */
object MimeTypes extends Enumeration {
  type MimeTypes = String

  val binarymsgpack = "application/x-msgpack"
  val text = "text/plain"
  val compressed7z = "application/x-7z-compressed"
  val atom = "application/atom"
  val atomcat = "application/atomcat+xml"
  val atomsrv = "application/atomserv+xml"
  val audio = "audio/basic"
  val avi = "video/x-msvideo"
  val binary = "application/octet-stream"
  val bmp = "image/x-ms-bmp"
  val css = "text/css"
  val csv = "text/csv"
  val gif = "image/gif"
  val gnumeric = "application/x-gnumeric"
  val gtar = "application/x-gtar"
  val hdf = "application/x-hdf"
  val hqx = "application/mac-binhex40"
  val html = "text/html"
  val ico = "image/x-icon"
  val ics = "text/calendar"
  val iso = "application/x-iso9660-image"
  val jar = "application/java-archive"
  val jnlp = "application/x-java-jnlp-file"
  val jpeg = "image/jpeg"
  val jpe = "image/jpeg"
  val jpg = "image/jpeg"
  val js = "application/x-javascript"
  val kar = "audio/midi"
  val key = "application/pgp-keys"
  val lzh = "application/x-lzh"
  val lzx = "application/x-lzx"
  val m3u = "audio/x-mpegurl"
  val m4a = "video/mp4"
  val m4b = "video/mp4"
  val m4v = "video/mp4"
  val midi = "audio/midi"
  val mpg = "video/mpeg"
  val oga = "audio/ogg"
  val ogg = "application/ogg"
  val patch = "text/x-diff"
  val pbm = "image/x-portable-bitmap"
  val pcx = "image/pcx"
  val pdf = "application/pdf"
  val png = "image/png"
  val ps = "application/postscript"
  val rdf = "application/rdf+xml"
  val rss = "application/rss+xml"
  val rtf = "application/rtf"
  val sh = "text/x-sh"
  val snd = "audio/basic"
  val svg = "image/svg+xml"
  val tar = "application/x-tar"
  val taz = "application/x-gtar"
  val tiff = "image/tiff"
  val torrent = "application/x-bittorrent"
  val wav = "audio/x-wav"
  val xsl = "application/xml"
  val zip = "application/zip"
}
